### ISSUE TITLE
Save each seed output separately according to the input seed file instead of 4D file named for last seed

### ISSUE THREAD

**Issue by grandjeanlab** [CoBrALab/RABIES#101]
**Describe the bug**
When running `analysis` with `--seed_list seed1 seed 2 seed3` only seed3 is processed, despite indication in 'rabies_analysis.log' that all seed have been input correctly (as shown in log header). 

**Describe RABIES call**
```
singularity run -B ${PROJECT}/template/roi:/roi_folder -B ${PROJECT}/template:/template -B ${bids_folder}:/rabies_in \
-B ${preprocess_folder}:/rabies_out -B ${current_confound}:/confound_out -B ${current_analysis}:/analysis_out \
/project/m/mchakrav/gjoanes/rabies.0.2.0-dev.simg -p MultiProc analysis /confound_out /analysis_out \
--seed_list ${roi_file_final}
```

where 
`echo $roi_file_final` 
returns 
```
/roi_folder/ACA_l.nii.gz /roi_folder/AI_l.nii.gz /roi_folder/AMG_l.nii.gz /roi_folder/CPu_l.nii.gz /roi_folder/dHC_l.nii.gz /roi_folder/MOp_l.nii.gz /roi_folder/RSP_l.nii.gz /roi_folder/S1bf_l.nii.gz /roi_folder/TH_l.nii.gz
```

**Attach log file**
[rabies_analysis.log](https://github.com/CoBrALab/RABIES/files/5862335/rabies_analysis.log)

**Attach QC_report**
According to log file, there should be 9 seeds. Only one  was ran.  

```
$ tree /scratch/m/mchakrav/gjoanes/multirat/analysis/aromas/01005/
/scratch/m/mchakrav/gjoanes/multirat/analysis/aromas/01005/
├── analysis_datasink
│   └── seed_correlation_maps
│       ├── _scan_info_subject_id0100500.session1_split_name_sub-0100500_ses-1_T2w
│       │   └── _run_1
│       │       └── TH_l_corr_map.nii.gz
│       ├── _scan_info_subject_id0100501.session1_split_name_sub-0100501_ses-1_T2w
│       │   └── _run_1
│       │       └── TH_l_corr_map.nii.gz
│       ├── _scan_info_subject_id0100502.session1_split_name_sub-0100502_ses-1_T2w
│       │   └── _run_1
│       │       └── TH_l_corr_map.nii.gz
│       ├── _scan_info_subject_id0100503.session1_split_name_sub-0100503_ses-1_T2w
│       │   └── _run_1
│       │       └── TH_l_corr_map.nii.gz
│       ├── _scan_info_subject_id0100504.session1_split_name_sub-0100504_ses-1_T2w
│       │   └── _run_1
│       │       └── TH_l_corr_map.nii.gz
│       ├── _scan_info_subject_id0100505.session1_split_name_sub-0100505_ses-1_T2w
│       │   └── _run_1
│       │       └── TH_l_corr_map.nii.gz
│       ├── _scan_info_subject_id0100506.session1_split_name_sub-0100506_ses-1_T2w
│       │   └── _run_1
│       │       └── TH_l_corr_map.nii.gz
│       ├── _scan_info_subject_id0100507.session1_split_name_sub-0100507_ses-1_T2w
│       │   └── _run_1
│       │       └── TH_l_corr_map.nii.gz
│       ├── _scan_info_subject_id0100508.session1_split_name_sub-0100508_ses-1_T2w
│       │   └── _run_1
│       │       └── TH_l_corr_map.nii.gz
│       └── _scan_info_subject_id0100509.session1_split_name_sub-0100509_ses-1_T2w
│           └── _run_1
│               └── TH_l_corr_map.nii.gz
├── rabies_analysis.log
└── rabies_analysis.pkl
```

**Additional context**
Thanks for looking into this.

**Comment by gdevenyi** [comment]
For clarity, what do you expect the output to look like if all the seeds were run, I don't know where to look in the output files list you've provided.

**Comment by gdevenyi** [comment]
I think I see the bug.

The seed_list is looped over to do the correlations, but only the last filename will be returned.

https://github.com/CoBrALab/RABIES/blob/3855af7405661af194732b7025cd717abb267d15/rabies/analysis_pkg/analysis_functions.py#L19-L28

**Comment by gdevenyi** [comment]
@grandjeanlab take a look inside that file, by my reading of the code, it appears there's a 4th dimension that will contain the different maps?

**Comment by Gab-D-G** [comment]
indeed the single file might have all of the seeds on the 4th dimension. This could be change to have a seperate file for each seed.

**Comment by grandjeanlab** [comment]
yep, indeed, seed output contains one volume per seed. It will be much easier to handle by the user if the seeds are split per volume : 
seed1_corr_map.nii.gz
seed2_corr_map.nii.gz
seed3_corr_map.nii.gz

**Comment by Gab-D-G** [comment]
Sounds good I'll address this in future updates.

**Comment by grandjeanlab** [comment]
could you also split DR_ICA output? easiest to use these readily for stats when they are split
