### ISSUE TITLE
--seed_list argument position

### ISSUE THREAD

**Issue by grandjeanlab** [CoBrALab/RABIES#102]
**Describe the bug**
When `--seed_list` is positioned as the last optional argument just before `confound_regression_out` and  `output_dir`, I get `rabies analysis: error: the following arguments are required: confound_regression_out, output_dir`

positioning `--seed_list` elsewhere solves it. 

Possibly due to fact that rabies interprets confound_regression and output_dir as seeds in the list in the following call.  `--seed_list seed1 confound_regression_out output_dir`

Maybe specify this in readme, or correct. 

**Describe RABIES call**
This bugs
`rabies -p MultiProc analysis --FC_matrix --DR_ICA --IC_file /groupshare/traaffneu/preclinimg/templates/my_templates/atlas/ABI_DR_zerbi15_200um.nii.gz --seed_list /groupshare/traaffneu/preclinimg/templates/my_templates/atlas/SBA_roi/MOp.nii.gz conf_drtest analysis_drtest `

This works
`rabies -p MultiProc analysis --seed_list /groupshare/traaffneu/preclinimg/templates/my_templates/atlas/SBA_roi/MOp.nii.gz --FC_matrix --DR_ICA --IC_file /groupshare/traaffneu/preclinimg/templates/my_templates/atlas/ABI_DR_zerbi15_200um.nii.gz  conf_drtest analysis_drtest`

**Attach log file**
No log is generated. Rabies crashes before with `rabies analysis: error: the following arguments are required: confound_regression_out, output_dir`

**Attach QC_report**
No QC

**Additional context**
No additional context

**Comment by gdevenyi** [comment]
This is a limitation of Python argparse I hae run into in other software. I'm not currently aware of a solution other than the workaround

**Comment by Gab-D-G** [comment]
Indeed, with your call, the --seed_list will take the directory paths as further seed files. I'm not aware either of an alternative than modifying the call to work around it.
