### ISSUE TITLE
resample --IC_file to commonspace resolution before running --DR_ICA

### ISSUE THREAD

**Issue by grandjeanlab** [CoBrALab/RABIES#103]
**Describe the bug**
When running `--DR_ICA` with external ICA template using the `--IC_file` argument, I get an error:
 `line 266, in sub_DR_ICA`
 `   all_IC_vectors[i, :] = (all_IC_array[:, :, :, i])[volume_indices]`
`IndexError: boolean index did not match indexed array along dimension 0; dimension is 57 but corresponding boolean dimension is 40`

when the `--IC_file` has the same dimension as the standard template. 
This issue is solved when I resample the myICAfile.nii.gz using one of the cleaned file from the confound regression.  
`3dresample -inset myICAfile.nii.gz -prefix resampledICAfile.nii.gz -master someConfoundRegressionFile.nii.gz` so that the ICA template has the same dimension as the cleaned timeseries (i.e., commonspace)

Would it be possible to resample `--IC_file` into commonspace the same way as seeds from `--seed_list` are before running the `--DR_ICA`?  

**Describe RABIES call**
`rabies -p MultiProc analysis --DR_ICA --IC_file /groupshare/traaffneu/preclinimg/templates/my_templates/atlas/ABI_DR_zerbi15_200um.nii.gz conf_drtest analysis_drtest`

**Attach log file**
[rabies_analysis.log](https://github.com/CoBrALab/RABIES/files/5871932/rabies_analysis.log)

**Attach QC_report**
NA
**Additional context**
NA

**Comment by Gab-D-G** [comment]
Sure, I will look into this!
