### ISSUE TITLE
Save all outputs in a software independent format (PKL is not Stable) 

### ISSUE THREAD

**Issue by grandjeanlab** [CoBrALab/RABIES#104]
**Describe the bug**
current outputs from `--FC_matrix` and `--DR_ICA` in `analysis` calls are in .pkl format. This is not easy to open for analysis/stats in other programs such as R and matlab. A CSV output would be more universal. 
Also, output  `combined_confounds.csv` from `preprocess` calls are given in CSV (thankfully), so this will also harmonize output :-) 

**Describe RABIES call**
`rabies -p MultiProc analysis --DR_ICA --IC_file /project/4180000.19/rabies_test/rsABI_DR_zerbi15_200um.nii.gz --FC_matrix conf_drtest analysis_drtest `

**Attach log file**
NA

**Attach QC_report**
tree ./matrix_data_file/
./matrix_data_file/
|-- _scan_info_subject_idjgrKCLmouse1.session1_split_name_sub-jgrKCLmouse1_ses-1_acq-RARE_T2w
|   |-- _run_1
|   |   `-- sub-jgrKCLmouse1_ses-1_task-rest_acq-EPI_run-1_bold_RAS_combined_cleaned_FC_matrix.pkl

tree ./DR_data_file
./DR_data_file
|-- _scan_info_subject_idjgrKCLmouse1.session1_split_name_sub-jgrKCLmouse1_ses-1_acq-RARE_T2w
|   |-- _run_1
|   |   `-- sub-jgrKCLmouse1_ses-1_task-rest_acq-EPI_run-1_bold_RAS_combined_cleaned_DR_ICA.pkl

**Additional context**
I am aware there are tricks to open pickles into R, but not every user will be, and, honestly, it remains a PITA.

**Comment by gdevenyi** [comment]
I'd like to generalize this issue. Pickle files are not version stable across Python and package versions.

All outputs should be saved in a generic format. CSV is obviously a safe format, but may be poorly performing. Another safe option would be feather.

**Comment by Gab-D-G** [comment]
Alright it should be manageable with CSV, I am not aware of feather though. What are its advantages over CSV?

**Comment by gdevenyi** [comment]
Faster, and with proper data-types built in. CSV is a bit ambiguous re: numbers vs strings that are composed of numbers, along with the issue of entries which contain commas.

https://blog.rstudio.com/2016/03/29/feather/

I'm not sure its worth adding a dependency though, depends on how big the data we're producing is.
