### ISSUE TITLE
specify output units from analysis

### ISSUE THREAD

**Issue by grandjeanlab** [CoBrALab/RABIES#105]
**Describe the bug**
Pretty fair to assume that seed and fc_matrix output are in pearson's r. It is less clear for the dr_ica output, and I couldn't get the answer from the code. fsl's `dual_regression` outputs both parameter estimates and z-stats. I assume you output the former, but I cannot be certain. 

In any case, it would be welcome to specify units for all outputs in README so users can report them accurately in their reports. 

**Describe RABIES call**
INA

**Attach log file**
NA

**Attach QC_report**
NA

**Additional context**
NA

**Comment by Gab-D-G** [comment]
Sounds good. It is indeed the former, with the code here https://github.com/CoBrALab/RABIES/blob/25095d782177f1279c3faf99164622b6e715884e/rabies/analysis_pkg/analysis_functions.py#L291. It is only giving the linear coefficients from the second linear regression. Overall, the current version of the analysis functionalities are preliminary, so there will be lots of updates required.
