### ISSUE TITLE
call to inexistant "antsRegistration_affine_SyN.sh" when using Affine

### ISSUE THREAD

**Issue by grandjeanlab** [CoBrALab/RABIES#112]
**Describe the bug**
in 0.2.1, using `-> coreg_script = Affine ` and `-> template_reg_script = Affine`, I get `main_wf.bias_cor_bold_main_wf.bias_correction_wf.bias_correction` crashes. 
Going through the log, the wf calls `antsRegistration_affine_SyN.sh`, but this shell script is neither in the $ANTSPATH or in the RABIES shell scripts. 

**Describe RABIES call**
rabies -p MultiProc preprocess --no_STC --TR=1.2s --coreg_script Affine --template_reg_script Affine /project/4180000.24/Bids /project/4180000.24/preprocess

**Attach log file**
[rabies_preprocess.log](https://github.com/CoBrALab/RABIES/files/6034274/rabies_preprocess.log)

**Attach QC_report**
N/A

**Additional context**
I think the issue is there, and also applies to SyN and Rigid
https://github.com/CoBrALab/RABIES/blob/master/rabies/preprocess_pkg/registration.py#L122

**Comment by Gab-D-G** [comment]
this is odd, I can't seem to reproduce the error when running it with Docker using only Affine transforms. You are running this in a Singularity container?

**Comment by gdevenyi** [comment]
sounds to me like this is being run without singularity based on the call presented. The antsRegistration_affine_SyN.sh and ants_generate_iterations.py scripts are found here, https://github.com/cobralab/minc-toolkit-extras

**Comment by grandjeanlab** [comment]
when running the singularity as a shell, I had omitted to export path to `minc-toolkit-extras`
This works now: 

singularity shell  /opt/rabies/0.2.1/rabies-0.2.1.simg

export ANTSPATH=/home/rabies/ants-v2.3.1/bin 

export RABIES_VERSION=0.2.1
export RABIES=/home/rabies/RABIES-0.2.1
export PYTHONPATH=$RABIES
export PATH=$PATH:$RABIES/bin
export PATH=$PATH:$RABIES/rabies/shell_scripts
export PATH=$RABIES/twolevel_ants_dbm:$PATH
export PATH=$RABIES/minc-toolkit-extras/:$PATH
