### ISSUE TITLE
unreliable analysis step 

### ISSUE THREAD

**Issue by grandjeanlab** [CoBrALab/RABIES#128]
**Describe the bug**
The `Analysis` call fails to output  a datasink folder despite no visible error in the log file. 
e.g. 
`tree $SCRATCH/multirat/analysis/WMCSFs/01001/`
/scratch/m/mchakrav/gjoanes/multirat/analysis/WMCSFs/01001/
├── rabies_analysis.log
└── rabies_analysis.pkl

**Describe RABIES call**
singularity run -B ${PROJECT}/template/roi:/roi_folder -B ${PROJECT}/template:/template -B ${bids_folder}:/rabies_in \
-B ${preprocess_folder}:/rabies_out -B ${current_confound}:/confound_out -B ${current_analysis}:/analysis_out \
/project/m/mchakrav/gjoanes/rabies-0.2.1.simg -p MultiProc analysis /confound_out /analysis_out \
--seed_list ${roi_file_final} --TR ${TR}s 

**Attach log file**
Here is the confound regression log, suggesting the previous step was run ok. 
[rabies_confound_regression.log](https://github.com/CoBrALab/RABIES/files/6323122/rabies_confound_regression.log)
Here is the analysis log. There is no error report. 
[rabies_analysis.log](https://github.com/CoBrALab/RABIES/files/6323120/rabies_analysis.log)

**Attach QC_report**
Preprocessing QA/QC seems fine. 

**Additional context**
I seem to this bug more often when WM/CSF/GSR confound regression than when I use aroma.

**Comment by grandjeanlab** [comment]
adding `--scale_min_memory 10` doesn't help either.

**Comment by gdevenyi** [comment]
Are you running this manually on Niagara without a job? I see no job logs anywhere.

Niagara will kill processes which use to much CPU on login nodes. That won't show in the logs.

**Comment by grandjeanlab** [comment]
That is the slurm output log on Niagara. I so no indications there of Niagara killing the processes. Where would this info be otherwise? 

[slurm-5156977.log](https://github.com/CoBrALab/RABIES/files/6326220/slurm-5156977.log)

**Comment by Gab-D-G** [comment]
From the slurm file, it shows that the pipeline somehow stops midway. That could be indeed because you are on a login now, which will simply stop the process as it is running without printing anything. To use the niagara clusters you need to call a .sh file with sbatch. If you want more details on this, we have a wiki page here https://github.com/CoBrALab/documentation/wiki/Running-RABIES-on-niagara describing the steps to do so. Basically, you need a file of this sort and call it with sbatch
```#!/bin/bash
#SBATCH --time=24:00:00
#SBATCH --nodes=1
#SBATCH --account=rrg-mchakrav-ab
module load singularity
singularity run -B /home/m/mchakrav/lanicupo/scratch/20201023_RABIES/nii_inputs:/nii_inputs:ro \
-B /home/m/mchakrav/lanicupo/scratch/20201023_RABIES/rabies_out:/rabies_out \
/home/m/mchakrav/lanicupo/scratch/20201023_RABIES/rabies.sif -p MultiProc preprocess /nii_inputs /rabies_out \
--disable_anat_preproc \
--anatomical_resampling 0.15x0.15x0.15 \
--autoreg

**Comment by grandjeanlab** [comment]
This is what I do. I used the following .sh file to submit with sbatch

[job_mr_rest_WM.txt](https://github.com/CoBrALab/RABIES/files/6326283/job_mr_rest_WM.txt)

**Comment by grandjeanlab** [comment]
running w/o multiprocess worked. thanks Gabe^2
I guess nothing we can do if this is builtin into nipype.
