### ISSUE TITLE
Consider  optimized_antsMultivariateTemplateConstruction for common space construction since DBM isn't needed

### ISSUE THREAD

**Issue by gdevenyi** [CoBrALab/RABIES#135]
This pipeline is an optimized version of antsMultivariateTemplateConstruction2.sh which uses antsRegistration_affine_SyN.sh

https://github.com/CoBrALab/optimized_antsMultivariateTemplateConstruction

**Comment by Gab-D-G** [comment]
This has been addressed in latest versions.
