### ISSUE TITLE
TR listed is incorrect when loading files in FSL

### ISSUE THREAD

**Issue by KarisColyerPatel** [CoBrALab/RABIES#151]
Hey there,

I have run both the preprocessing and regression steps on my data, and I am now in the process of completing my analysis with FSL Feat. However, when I add the 4d input data the TR that is shown is incorrect. Currently, in FSL Feat the TR is showing as 1.0 but it is actually 0.801! 

Thanks,

Karis

**Comment by gdevenyi** [comment]
Can you please check that your input files have the correct TR set before RABIES.

**Comment by KarisColyerPatel** [comment]
Just checked :)

data_type      FLOAT32
dim1           108
dim2           17
dim3           108
dim4           437
datatype       16
pixdim1        0.300000
pixdim2        1.000000
pixdim3        0.300000
pixdim4        0.801000
cal_max        0.0000
cal_min        0.0000
file_type      NIFTI-1+

**Comment by KarisColyerPatel** [comment]
Ow sorry, sure please find below:

Input file:

base) c12630594@tux13psy:~/Desktop/bids/sub-01/ses-01/func$ fslinfo sub-01_ses-01_task-oace_run-1_bold.nii.gz 
data_type      FLOAT32
dim1           108
dim2           17
dim3           108
dim4           437
datatype       16
pixdim1        0.300000
pixdim2        1.000000
pixdim3        0.300000
pixdim4        0.801000
cal_max        0.0000
cal_min        0.0000
file_type      NIFTI-1+

RABIES output file:

(base) c12630594@tux13psy:~/Desktop/confound_regression_outputs/confound_regression_datasink/cleaned_timeseries/_scan_info_subject_id01.session01_split_name_sub-01_ses-01_T1ww/_run_1$ fslinfo sub-01_ses-01_task-oace_run-1_bold_combined_aroma_cleaned.nii.gz 
data_type      INT16
dim1           60
dim2           31
dim3           47
dim4           437
datatype       4
pixdim1        0.300000
pixdim2        1.000000
pixdim3        0.300000
pixdim4        1.000000
cal_max        0.0000
cal_min        0.0000
file_type      NIFTI-1+

**Comment by gdevenyi** [comment]
Right, so it's worth trying to trace the path this file goes through to see when this change happens.

@Gab-D-G where do we look to find all the "versions" of an input file `sub-01_ses-01_task-oace_run-1_bold.nii.gz` passes through on its way to output?

**Comment by KarisColyerPatel** [comment]
Hey, 

So I am actually having issues running my analysis in FSL Feat with the output from the regression step. The reason I am following up here is because I have also found where the TR value changes from 0.801 to 1.0. Within the confound regression output/confound_regression_datasink there are two folders: within the 1st folder 'aroma_out' there is a file called sub-01_ses-01_task-oace_run-1_bold_combined_aroma.nii.gz. This file has a TR of 0.801.

**Comment by Gab-D-G** [comment]
Thanks for pointing this out @KarisColyerPatel ! It is normal the the file after regression is very different because the mean image was removed, so you only have timeseries. However it seems like you've found out where the metadata is not properly saved for the TR info, so I'll fix this in the next updates!
