### ISSUE TITLE
rabies on oblique data

### ISSUE THREAD

**Issue by grandjeanlab** [CoBrALab/RABIES#160]
**Describe the bug**
I've had ITK I/O error  when my scans are considered "oblique" during preprocessing for both anat and func
I solved this running deblique first. 

excerpt error from log file 
itk::ExceptionObject (0x55e35c524820)
Location: "unknown" 
File: /opt/ANTs/build/ITKv5/Modules/IO/NIFTI/src/itkNiftiImageIO.cxx
Line: 1972
Description: itk::ERROR: ITK only supports orthonormal direction cosines.  No orthonormal definition found!

**Describe RABIES call**
Running oblique2cartesian on anat and func before rabies solves it. 
e.g. 3dWarp -oblique2card -prefix ${output} ${input}

**Attach log file**
attached

**Attach QC_report**
N/A

**Additional context**
Implementing deoblique step may reduce risk other users also have oblique data run into issues. 
For instance, brkraw will generate oblique data, so issue might apply to several users.

**Comment by gdevenyi** [comment]
We have seen this reported in one other case.

Since this is a pretty invasive modification of the original data, I think we should keep this off by default and try to detect oblique data, and provide a big warning/error when running.

The proper solution should be to collect non-oblique data, etc.

**Comment by gdevenyi** [comment]
@grandjeanlab can I please get a fslheader or such on the weird NIFTI file? Thanks.

**Comment by grandjeanlab** [comment]
sizeof_hdr	348
data_type	INT16
dim0		4
dim1		60
dim2		30
dim3		20
dim4		720
dim5		1
dim6		1
dim7		1
vox_units	mm
time_units	s
datatype	4
nbyper		2
bitpix		16
pixdim0		1.000000
pixdim1		0.283214
pixdim2		0.300042
pixdim3		0.450375
pixdim4		1.000000
pixdim5		1.000000
pixdim6		1.000000
pixdim7		1.000000
vox_offset	352
cal_max		0.000000
cal_min		0.000000
scl_slope	0.016832
scl_inter	0.000000
phase_dim	0
freq_dim	0
slice_dim	3
slice_name	alternating_increasing
slice_code	3
slice_start	0
slice_end	19
slice_duration	0.050000
toffset		0.000000
intent		Unknown
intent_code	0
intent_name	
intent_p1	0.000000
intent_p2	0.000000
intent_p3	0.000000
qform_name	Unknown
qform_code	0
qto_xyz:1	0.283006 0.000091 0.017245 -8.631000 
qto_xyz:2	-0.010844 0.004830 0.449987 -3.371000 
qto_xyz:3	-0.000089 -0.300003 0.007250 6.291000 
qto_xyz:4	0.000000 0.000000 0.000000 1.000000 
qform_xorient	Left-to-Right
qform_yorient	Superior-to-Inferior
qform_zorient	Posterior-to-Anterior
sform_name	Unknown
sform_code	2
sto_xyz:1	0.283000 -0.000000 0.017000 -8.631000 
sto_xyz:2	-0.011000 0.005000 0.450000 -3.371000 
sto_xyz:3	-0.000000 -0.300000 0.007000 6.291000 
sto_xyz:4	0.000000 0.000000 0.000000 1.000000 
sform_xorient	Left-to-Right
sform_yorient	Superior-to-Inferior
sform_zorient	Posterior-to-Anterior
file_type	NIFTI-1+
file_code	1
descrip		
aux_file	

Converted using [brkraw](https://github.com/BrkRaw/brkraw)

**Comment by gdevenyi** [comment]
@grandjeanlab did you do anything to these files after brkraw? A look over the brkraw code says I expect
`qform_code = 1` and `sform_code = 0` but you have `qform_code = 0` and `sform_code = 2`

**Comment by gdevenyi** [comment]
followup @grandjeanlab

**Comment by grandjeanlab** [comment]
No, we ran vanilla brkraw 0.3.4  without additional argument.

**Comment by gdevenyi** [comment]
I can confirm that our conversions also produce qform/sform that doesn't correspond to the code. I think I blame nibabel somewhere inside brkraw.

**Comment by gdevenyi** [comment]
The upstream issue with SimpleITK/ITK has been resolved and will eventually make it into an ITK release: https://github.com/InsightSoftwareConsortium/ITK/commit/6278c4171f697649da5b3136214cfbb8e37aab00
