### ISSUE TITLE
dual_ICA not working with custom prior_maps

### ISSUE THREAD

**Issue by grandjeanlab** [CoBrALab/RABIES#164]
**Describe the bug**
Running dual_ICA with embedded prior_maps works like a charm. Trying custom prior_maps fails. Possibly unrelated to prior_maps, as it can be used to run DR_ICA flawlessly. 

**Describe RABIES call**
singularity run -B ${bids_folder}:/rabies_in:ro \
-B ${preprocess_folder}:/rabies_out \
-B ${confound_folder}:/confound \
-B ${analysis_folder}:/analysis \
-B /project/m/mchakrav/gjoanes/template/:/template \
/project/m/mchakrav/gjoanes/rabies-0.3.0.simg analysis /confound /analysis --DR_ICA --IC_file /template/DSURQE_100micron_DRICA.nii.gz --dual_ICA 10 --prior_maps /template//DSURQE_100micron_DRICA.nii.gz --prior_bold_idx  1 2 3

**Attach log file**
[rabies_analysis.log](https://github.com/CoBrALab/RABIES/files/6894906/rabies_analysis.log)

**Attach QC_report**
NA

**Additional context**
Link to the custom prior_maps in DRUSQE space. 
https://surfdrive.surf.nl/files/index.php/s/5L06YzzIS548gy8

**Comment by Gab-D-G** [comment]
Hi, this has been addressed in the version 0.3.0, the version 0.2.5 still has that bug.

**Comment by grandjeanlab** [comment]
docker image latest wasn't up to date. I will rebuild an image now and test.

**Comment by Gab-D-G** [comment]
ah! I'll update teh latest version to 0.3.0 as well.
