### ISSUE TITLE
RABIES 0.3.0 with custom template

### ISSUE THREAD

**Issue by grandjeanlab** [CoBrALab/RABIES#165]
**Describe the bug**
Running RABIES 0.3.0 with custom template (rat template) fails. The same command in RABIES 0.2.1 works, suggesting it isn't issue with custom template. 
The same singularity image has been used in mice and works. 

This suggest issue is linked to loading custom template in RABIES 0.3.0, but not in 0.2.1. 

**Describe RABIES call**
/project/m/mchakrav/gjoanes/rabies-0.3.0.simg -p MultiProc preprocess /rabies_in /rabies_out \
--template_reg_script multiRAT \
--coreg_script light_SyN \
--no_STC \
--anat_template ${template} \
--brain_mask ${mask} \
--WM_mask ${wm} \
--CSF_mask ${csf} \
--vascular_mask ${csf} \
--labels ${atlas} \
--TR ${TR}s \
--commonspace_resampling 0.3x0.3x0.3

**Attach log file**
[rabies_preprocess.log](https://github.com/CoBrALab/RABIES/files/6894966/rabies_preprocess.log)

**Attach QC_report**
NA

**Additional context**
preprocessed data under `$SCRATCH/multirat/preprocess/01013`

**Comment by Gab-D-G** [comment]
The version of this log report is 0.2.5. Are you sure this is run with the right version?

**Comment by grandjeanlab** [comment]
issue was with 0.2.5, and due to dockerhub latest not being updated. 0.3.0 works great
