### ISSUE TITLE
broken analysis_wf.seed_based_FC 0.2.1 => 0.3.1 

### ISSUE THREAD

**Issue by grandjeanlab** [CoBrALab/RABIES#169]
**Describe the bug**
The same analysis call with SBA  in 0.3.1 experience registration error, while it worked well under 0.2.1.  Other assets are identical. preprocess/confound executed without errors.  

Log file indicates : 
  File "/home/rabies/RABIES/rabies/analysis_pkg/analysis_functions.py", line 35, in seed_corr
    os.system('antsApplyTransforms -i {} -r {} -o {} -n GenericLabel' %
TypeError: not all arguments converted during string formatting

**Describe RABIES call**
`singularity run -B ${PROJECT}/template/roi:/roi_folder -B ${PROJECT}/template:/$
$-B ${current_analysis}:/analysis_out \
/project/m/mchakrav/gjoanes/rabies-0.3.1.simg analysis /confound_out /analysis_$
--seed_list ${roi_file_final} --TR ${TR}s`

**Attach log file**
[rabies_analysis.log](https://github.com/CoBrALab/RABIES/files/6910936/rabies_analysis.log)

**Attach QC_report**
NA. scans passed QA

**Additional context**
Folder location on Niagara
`/scratch/m/mchakrav/gjoanes/multirat/preprocess/01015`
`/scratch/m/mchakrav/gjoanes/multirat/confound/aromas/01015`
`/scratch/m/mchakrav/gjoanes/multirat/analysis/aromas/01015`

**Comment by gdevenyi** [comment]
> Describe RABIES call
Please provide the version with expanded variables.

**Comment by gdevenyi** [comment]
@Gab-D-G this looks like you've got broken string-formatting, where you've partially switched from "old style" formatting. This should be a f-string now like the rest of the conversion you did.
