### ISSUE TITLE
Files from the same atlas not overlapping

### ISSUE THREAD

**Issue by The-Archon-AI** [CoBrALab/RABIES#174]
Hi everyone! I've been having some issues as described below:

**Describe the bug**
While attempting to use the SIGMA atlas I get errors like "x does not seem to overlap with provided template". 

**Describe RABIES call**
Include a copy of the command call you executed from the terminal, and any additional information that could be relevant to your execution.

I'm running rabies on docker and through windows Powershell:

```
docker run --rm  -it  `
    -v C:\Users\dortu\OneDrive\Documentos\Lab_Files\Atlas\SIGMA_Wistar_Rat_Brain_TemplatesAndAtlases_Version1.1\SIGMA_Rat_Anatomical_Imaging\SIGMA_Rat_Anatomical_InVivo_Template\SIGMA_InVivo_Brain_Template.nii:/template/SIGMA_InVivo_Brain_Template.nii `
    -v C:\Users\dortu\OneDrive\Documentos\Lab_Files\Atlas\SIGMA_Wistar_Rat_Brain_TemplatesAndAtlases_Version1.1\SIGMA_Rat_Anatomical_Imaging\SIGMA_Rat_Anatomical_InVivo_Template\SIGMA_InVivo_Brain_Mask.nii:/mask/SIGMA_InVivo_Brain_Mask.nii `
    -v C:\Users\dortu\OneDrive\Documentos\Lab_Files\Atlas\SIGMA_Wistar_Rat_Brain_TemplatesAndAtlases_Version1.1\SIGMA_Rat_Anatomical_Imaging\SIGMA_Rat_Anatomical_InVivo_Template\SIGMA_InVivo_WM_bin.nii.gz:/wm/SIGMA_InVivo_WM_bin.nii.gz `
    -v C:\Users\dortu\OneDrive\Documentos\Lab_Files\Atlas\SIGMA_Wistar_Rat_Brain_TemplatesAndAtlases_Version1.1\SIGMA_Rat_Anatomical_Imaging\SIGMA_Rat_Anatomical_InVivo_Template\SIGMA_InVivo_CSF_bin.nii.gz:/csf/SIGMA_InVivo_CSF_bin.nii.gz `
    -v C:\Users\dortu\OneDrive\Documentos\Lab_Files\Atlas\SIGMA_Wistar_Rat_Brain_TemplatesAndAtlases_Version1.1\SIGMA_Rat_Brain_Atlases\SIGMA_Anatomical_Atlas\SIGMA_Anatomical_Brain_Atlas.nii:/atlas/SIGMA_Anatomical_Brain_Atlas.nii `
    -v /c//input:/input:ro `
    -v /c//rabies:/output gabdesgreg/rabies:latest `
    -p MultiProc preprocess /input /output `
    --coreg_script SyN `
    --no_STC `
    --anat_template /template/SIGMA_InVivo_Brain_Template.nii  `
    --brain_mask /mask/SIGMA_InVivo_Brain_Mask.nii `
    --CSF_mask /csf/SIGMA_InVivo_CSF_bin.nii.gz `
    --WM_mask /wm/SIGMA_InVivo_WM_bin.nii.gz `
    --vascular_mask /csf/SIGMA_InVivo_CSF_bin.nii.gz `
    --labels /atlas/SIGMA_Anatomical_Brain_Atlas.nii `
    --commonspace_resampling 0.3x0.3x0.3

```
**Attach log file**

Here is the error I am currently facing (for some reason neither error shows in the log files so I copied the terminal output into these .txt files):
[rabies_log_1.txt](https://github.com/CoBrALab/RABIES/files/7140296/rabies_log_1.txt)

Here is the error I had before BETing the _Invivo_ brain template:
[rabies_log_2.txt](https://github.com/CoBrALab/RABIES/files/7140314/rabies_log_2.txt)

**Additional context**

I used to get this error with the anatomic atlas and the _Invivo_ brain template not overlapping, so I ran a BET on the brain template and the error stopped, however, now I am getting these other "does not seem to overlap" errors with the masks (probably due to the BET itself). Is there another manipulation I need to do on the atlas files for rabies to recognize it as "overlapping"?

Thanks in advance.

Diego

**Comment by Gab-D-G** [comment]
RABIES assumes that the template files have the same origin and same directionalities. This error means that somehow your files don't. A way to ensure the metadata is shared among your template files would be to run antsApplyTransform without applying any transform, with your template as reference, for each of your other files. SimpleITK, and probably other softwares could probably handle this too. The call with antsApplyTransform should resemble 
```
antsApplyTransform -i $mask_file -r $template_file -o $resampled_mask -n GenericLabel -v
```

**Comment by The-Archon-AI** [comment]
It worked, thank you! I think it was an issue with the atlas itself.

**Comment by nmskhan** [comment]
Hi Diego
Would you mind in providing the rat atlas used in your analysis (all five files)? I am interested in using them. 
Thanks
Ned

**Comment by dortuzarm** [comment]
> Hi Diego Would you mind in providing the rat atlas used in your analysis (all five files)? I am interested in using them. Thanks Ned

Sure, you can find them here. 

https://www.nitrc.org/frs/?group_id=1375

**Comment by nmskhan** [comment]
Thank you for quick reply, I will download them. Thanks
Ned
