### ISSUE TITLE
confound_correction failure on test_dataset

### ISSUE THREAD

**Issue by grandjeanlab** [CoBrALab/RABIES#187]
**Describe the bug**
Using the test_dataset provided on this repo, I tried Rabies 0.3.4. The confound_correction step keeps failing. 
behavior seen with other datasets too (e.g. multiRat). Preprocessing passes QC, so seemingly not the issue. 
Confound_correction steps with AROMA fail for other reasons, see #182 

**Describe RABIES call**
singularity run -B /scratch/m/mchakrav/gjoanes/misc/ds_extract/test_dataset:/rabies_in:ro -B /scratch/m/mchakrav/gjoanes/misc/preprocess/test_dataset:/rabies_out \
-B /scratch/m/mchakrav/gjoanes/misc/confound/test_dataset:/confound /project/m/mchakrav/gjoanes/rabies-0.3.4.simg -p MultiProc --scale_min_memory 10 \
confound_correction /rabies_out /confound \
--highpass 0.01 --smoothing_filter 0.3 --lowpass 0.1 --conf_list WM_signal CSF_signal mot_6

I try this call with and without read_datasink in case the failure is due to reprocessing of some steps. 

**Attach log file**
Log file without and with read_datasink at attached

[rabies_confound_correction_nodatasink.log](https://github.com/CoBrALab/RABIES/files/7473959/rabies_confound_correction_nodatasink.log)
[rabies_confound_correction_readdatasink.log](https://github.com/CoBrALab/RABIES/files/7473960/rabies_confound_correction_readdatasink.log)

**Attach QC_report**
N/A

**Additional context**
Full call on Niagara

#!/bin/sh
#SBATCH --time=12:00:00
#SBATCH --nodes=1
#SBATCH --account=rrg-mchakrav-ab
#SBATCH --ntasks=20

#dataset name
bidsID='test_dataset'

#init folder name
bids_folder=$SCRATCH/misc/ds_extract/${bidsID}
preprocess_folder=$SCRATCH/misc/preprocess/${bidsID}
confound_folder=$SCRATCH/misc/confound/${bidsID}_readdatasink

#init folders
rm -rf ${preprocess_folder}
rm -rf ${confound_folder}
mkdir -p ${preprocess_folder}
mkdir -p ${confound_folder}

#preprocessing
singularity run -B ${bids_folder}:/rabies_in:ro -B ${preprocess_folder}:/rabies_out \
/project/m/mchakrav/gjoanes/rabies-0.3.4.simg -p MultiProc --scale_min_memory 10 \
preprocess /rabies_in /rabies_out

#confound
singularity run -B ${bids_folder}:/rabies_in:ro -B ${preprocess_folder}:/rabies_out \
-B ${confound_folder}:/confound /project/m/mchakrav/gjoanes/rabies-0.3.4.simg -p MultiProc --scale_min_memory 10 \
confound_correction /rabies_out /confound \
--highpass 0.01 --smoothing_filter 0.3 --lowpass 0.1 --conf_list WM_signal CSF_signal mot_6

**Comment by Gab-D-G** [comment]
Hi, the test dataset is meant for preprocessing mainly. It is a shrunked dataset with only 18 timespoints in the EPI, so filtering at low frequencies can't be applied because it lacks enough data samples.
