### ISSUE TITLE
Testing rabbies install on test dataset fails (UnsharpMask issue)

### ISSUE THREAD

**Issue by benhibou** [CoBrALab/RABIES#202]
**Describe the bug**
 I am testing a rabies install on Ubuntu Linux version 16.04.7 and it fails on the test data set

**Describe RABIES call**
rabies -p MultiProc preprocess test_dataset/ preprocess_outputs/ --TR 1.0s --no_STC --debug
Other simpler version like:
rabies preprocess test_dataset/ preprocess_outputs/
fails with the same error.
**Attach log file**
[rabies_preprocess.log](https://github.com/CoBrALab/RABIES/files/7943698/rabies_preprocess.log)

**Attach QC_report**
[QC_rep.tar.zip](https://github.com/CoBrALab/RABIES/files/7943747/QC_rep.tar.zip)

**Additional context**

Thank you in advance for your help!

**Comment by gdevenyi** [comment]
The log file does not appear to contain the words "UnsharpMask" so it's a bit hard to diagnose here.

However this sounds like your ants version is too old.

**Comment by gdevenyi** [comment]
https://github.com/ANTsX/ANTs/issues/984

**Comment by benhibou** [comment]
line 12069 in the log file indicates:
Operation UnsharpMask not found or not supported for dimension 3
But curiously there is on line 12062 an UnsharpMask command directly following an ImageMath command there and not the one that was issued at line 12068. I guess there was a little lag in the issuing of the error message.

In any case I must first try your suggestion to use a newer version of ants.

I'll let you know. Thanks.

**Comment by gdevenyi** [comment]
Too old a version of ANTs. Use the containers, or update your local version available
