### ISSUE TITLE
Permission issues

### ISSUE THREAD

**Issue by KarisColyerPatel** [CoBrALab/RABIES#256]
I have been trying to run the preprocessing step using docker on my universities server with the following command:

```
docker run -it --rm -v $PWD/input_BIDS:/input_BIDS:ro -v $PWD/preprocess_outputs:/preprocess_outputs/ gabdesgreg/rabies:0.4.7 -p MultiProc preprocess /input_BIDS/ /preprocess_outputs/ --apply_STC --TR 0.801
```

However, I appear to have a permission issue:
```
Traceback (most recent call last):
  File "/home/rabies/miniforge/bin/rabies", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/rabies/RABIES/scripts/rabies", line 3, in <module>
    execute_workflow()
  File "/home/rabies/RABIES/rabies/run_main.py", line 28, in execute_workflow
    log = prep_logging(opts, output_folder)
  File "/home/rabies/RABIES/rabies/run_main.py", line 79, in prep_logging
    with open(cli_file, 'wb') as handle:
PermissionError: [Errno 13] Permission denied: '/preprocess_outputs/rabies_preprocess.pkl'
```

I asked for assistance from IT support and they observed the following:

E: Could not open lock file /var/lib/dpkg/lock-frontend - open (13: Permission denied)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?

They also check whether I needed to be a sudo user but this did not resolve the issue. For all my folders I have  -d -r -w (dir/read/write) so I should not be having permission issues. 

Finally, they tried to make the file, but RABIES complained about the former existing file: /rabies_preprocess.pkl'

Any suggestions would be appreciated!

**Comment by gdevenyi** [comment]
Docker itself has significant permissions compilations, as everything is classically run as root. Have you tried instead using singularity, which greatly simplifies this part, by wrapping everything to run as your user?

The docs explicitly recommend singularity,
https://rabies.readthedocs.io/en/stable/installation.html

**Comment by KarisColyerPatel** [comment]
Unfortunately, I was informed by our department there is no release candidate for Ubuntu 22.04, so I should try using docker.

There is the possibility to get singularity running but I would need to build it from source code. I do not have the expertise to do this and the IT department which provides support does not have the time available to help with this!

**Comment by gdevenyi** [comment]
> Unfortunately, I was informed by our department there is no release candidate for Ubuntu 22.04, so I should try using docker.

There's a full official release... https://github.com/sylabs/singularity/releases
> singularity-ce_3.10.4-jammy_amd64.deb

What I'll say here, I don't think this is a RABIES bug, but rather just an issue of exactly how docker is being used combined with various settings. As such its difficult to help, because you don't own your machine to do what you want, I suggest pushing to get singularity given the new info I've provided.

**Comment by biancadepifanio** [comment]
Hi, everyone :) I am also getting the same exact error using docker. Maybe it's not a RABIES bug, but still, something to look more into.

**Comment by biancadepifanio** [comment]
Hello everyone, I think this problem is a folder issue, and there's a workaround for it (meaning that  it's not necessary to install singularity). I had it (as I said before) with one dataset, but after changing the folder where I wanted to run rabies, this error disappeared and rabies run smoothly.
