### ISSUE TITLE
SimpleITK ImageFileReader_Execute error

### ISSUE THREAD

**Issue by archang** [CoBrALab/RABIES#264]
**Describe the bug**
Hi there, after successfully running the preprocessing and confound correction package using Docker on a custom set of template/label files, I am now attempting to run a basic FC_matrix analysis. I am running into an SimpleITK ImageFileReader_Execute error saying that my label file does not exist ("sitk::ERROR: The file "rat/Atlas.nii.gz" does not exist.") This is despite explicitly attaching a volume to my docker run command that maps the directory on my local file system to the docker container. I assume as the preprocessing package was able to read my custom template/label files that the analysis package should as well (my labels file is stored locally at $PWD/rat/Atlas.nii.gz, and permissions were set to chmod 777, and I am running as root)

**Describe RABIES call**
```
docker run -it --rm -v $PWD/input_BIDS:/input_BIDS:ro -v $PWD/rat:/home/rabies/rat:ro -v $PWD/preprocess_outputs:/preprocess_outputs/ -v $PWD/confound_correction_outputs:/confound_correction_outputs/ -v $PWD/analysis_outputs:/analysis_outputs/ gabdesgreg/rabies:0.4.8 -p MultiProc analysis /confound_correction_outputs /analysis_outputs/ --FC_matrix --ROI_csv rat/Atlas.nii.gz
```

**Attach log file**
[rabies_analysis.log](https://github.com/CoBrALab/RABIES/files/10512256/rabies_analysis.log)

**Additional context**
Something else that I tried was to edit my RABIES analysis call --ROI_csv argument from "rat/Atlas_FAKE.nii.gz" to "rat/Atlas_fake.nii.gz" to see how providing an erroneous filepath would change the error. Here is the log file for that command:

[rabies_analysis_with_fake_labels.log](https://github.com/CoBrALab/RABIES/files/10512298/rabies_analysis_with_fake_labels.log)

It still says "sitk::ERROR: The file "rat/Atlas.nii.gz" does not exist," even though I am not specifically calling to use "rat/Atlas.nii.gz" but rather "rat/Atlas_FAKE.nii.gz"

**Comment by gdevenyi** [comment]
Why are you supplying a `.nii.gz` file to the command-line option `--ROI_csv`

The documentation:
```
  --ROI_csv ROI_CSV     A CSV file with the ROI names matching the ROI index numbers in the atlas labels Nifti file. 
```

**Comment by gdevenyi** [comment]
The preprocess options are loaded from a pickle file:
https://github.com/CoBrALab/RABIES/blob/53c12ba2d9365621dba6edfff6157c4d7368c497/rabies/run_main.py#L234-L255

So at some point you set `rat/Atlas.nii.gz` in your settings earlier than this call.

**Comment by archang** [comment]
> Why are you supplying a `.nii.gz` file to the command-line option `--ROI_csv`
> 
> The documentation:
> 
> ```
>   --ROI_csv ROI_CSV     A CSV file with the ROI names matching the ROI index numbers in the atlas labels Nifti file. 
> ```

I was a little uncertain about supplying a 'csv' versus a 'nii.gz' because the documentation specified that the default value provided was a 'nii.gz' ("default: /home/gabriel/.local/share/rabies/DSURQE_40micron_labels.nii.gz"), but I will certainly use 'csv' moving forward.

**Comment by archang** [comment]
> The preprocess options are loaded from a pickle file:
> 
> https://github.com/CoBrALab/RABIES/blob/53c12ba2d9365621dba6edfff6157c4d7368c497/rabies/run_main.py#L260-L280
> 
> So at some point you set `rat/Atlas.nii.gz` in your settings earlier than this call.

I'm not sure at what point I would have set `rat/Atlas.nii.gz` in my settings prior to that call. In all, I only ran three commands, each corresponding to preprocess, confound correction & analysis.

I am looking into whether or not this is a Docker related issue. We are also running this on an AWS EC2 instance. I understand it is recommended to use Singularity over Docker, so this is also something that we will consider.

**Comment by gdevenyi** [comment]
> I was a little uncertain about supplying a 'csv' versus a 'nii.gz' because the documentation specified that the default value provided was a 'nii.gz' ("default: /home/gabriel/.local/share/rabies/DSURQE_40micron_labels.nii.gz"), but I will certainly use 'csv' moving forward.

Can you cite that documentation, I don't see it.

**Comment by gdevenyi** [comment]
> I'm not sure at what point I would have set rat/Atlas.nii.gz in my settings prior to that call. In all, I only ran three commands, each corresponding to preprocess, confound correction & analysis.

The code block is here, 

https://github.com/CoBrALab/RABIES/blob/c6c83d0e0a2991964d9afcfbae0057da02ce2caf/rabies/analysis_pkg/main_wf.py#L70-L85

Can you share your logs from the preprocess step.

**Comment by archang** [comment]
> > I was a little uncertain about supplying a 'csv' versus a 'nii.gz' because the documentation specified that the default value provided was a 'nii.gz' ("default: /home/gabriel/.local/share/rabies/DSURQE_40micron_labels.nii.gz"), but I will certainly use 'csv' moving forward.
> 
> Can you cite that documentation, I don't see it.

[Here](https://rabies.readthedocs.io/en/stable/running_the_software.html) under rabies analysis --help

**Comment by archang** [comment]
> 



> > I'm not sure at what point I would have set rat/Atlas.nii.gz in my settings prior to that call. In all, I only ran three commands, each corresponding to preprocess, confound correction & analysis.
> 
> The code block is here,
> 
> https://github.com/CoBrALab/RABIES/blob/c6c83d0e0a2991964d9afcfbae0057da02ce2caf/rabies/analysis_pkg/main_wf.py#L70-L85
> 
> Can you share your logs from the preprocess step.

[rabies_preprocess.log](https://github.com/CoBrALab/RABIES/files/10514210/rabies_preprocess.log)

**Comment by gdevenyi** [comment]
`-> labels = rat/Atlas.nii.gz `

As for the documentation, does the output from the real program --help say that?

**Comment by archang** [comment]
The output from "docker run gabdesgreg/rabies:0.4.8 preprocess --help" shows that the default value for argument --labels is  "/home/rabies/.local/share/rabies/DSURQE_40micron_labels.nii.gz"

**Comment by gdevenyi** [comment]
And --ROI_CSV default from help?

**Comment by archang** [comment]
> And --ROI_CSV default from help?

The output from "docker run gabdesgreg/rabies:0.4.8 analysis --help" shows that the argument for --ROI_csv is 
/home/gabriel/.local/share/rabies/DSURQE_40micron_labels.nii.gz

**Comment by Gab-D-G** [comment]
Hi, the `--labels` file should be a nifti with the atlas labels, and is provided during the preprocessing step. However, at each subsequent stage, inputs/outputs from previous steps are checked to make sure they are consistent, and within a docker container this implies that your paths must be consistent between the RABIES stages. Can you double check that the file system path from your preprocessing step linking your label file is the same during your analysis call?

**Comment by archang** [comment]
> Hi, the `--labels` file should be a nifti with the atlas labels, and is provided during the preprocessing step. However, at each subsequent stage, inputs/outputs from previous steps are checked to make sure they are consistent, and within a docker container this implies that your paths must be consistent between the RABIES stages. Can you double check that the file system path from your preprocessing step linking your label file is the same during your analysis call?

I have verified that no changes were made to any directory or filepath from step to step. Below are the exact commands used for the preprocessing, confound correction & analysis steps (I am working on getting the proper csv file generated for the --ROI_csv argument in analysis, but that should not affect whether or not rat/Atlas.nii.gz is able to be found)

Preprocess: 

docker run -it --rm -v $PWD/input_BIDS:/input_BIDS:ro -v $PWD/rat:/home/rabies/rat:ro -v $PWD/preprocess_outputs:/preprocess_outputs/ gabdesgreg/rabies:0.4.8 -p MultiProc preprocess /input_BIDS/ /preprocess_outputs/ --apply_STC --bold_only --anat_template rat/Atlas_ref.nii.gz --brain_mask rat/Atlas_bin.nii.gz --WM_mask rat/rat_wm_mask.nii.gz --CSF_mask rat/rat_ventricle_mask.nii.gz --vascular_mask  rat/Atlas_bin.nii.gz --labels rat/Atlas.nii.gz --TR 3.0,masking=true,brain_extraction=false,template_registration=SyN,fast_commonspace=false 

Confound corr: 

docker run -it --rm -v $PWD/input_BIDS:/input_BIDS:ro -v $PWD/rat:/home/rabies/rat:ro -v $PWD/preprocess_outputs:/preprocess_outputs/ -v $PWD/confound_correction_outputs:/confound_correction_outputs/ gabdesgreg/rabies:0.4.8 -p MultiProc confound_correction /preprocess_outputs/ /confound_correction_outputs/ --conf_list WM_signal CSF_signal mot_6 --smoothing_filter 0.3 

Analysis: 

docker run -it --rm -v $PWD/input_BIDS:/input_BIDS:ro -v $PWD/rat:/home/rabies/rat:ro -v $PWD/preprocess_outputs:/preprocess_outputs/ -v $PWD/confound_correction_outputs:/confound_correction_outputs/ -v $PWD/analysis_outputs:/analysis_outputs/ gabdesgreg/rabies:0.4.8 -p MultiProc analysis /confound_correction_outputs /analysis_outputs/ --FC_matrix --ROI_csv rat/Atlas.nii.gz

**Comment by Gab-D-G** [comment]
My second best bet then would be to check whether it is a relative path error. You are providing a relative path `rat/Atlas.nii.gz` assuming it can be access from `/home/rabies`, but I would recommend in general providing absolute paths for accessing any files. Could you try again with an absolute path instead? Otherwise I can't know what's causing the issue simply from the log unfortunately.

**Comment by archang** [comment]
I will try running the preprocess package again with the absolute path to Atlas.nii.gz provided. This way, the path to Atlas.nii.gz in the pickled output to the analysis package should be updated. I will update after the preprocess package completes (~1-2 days)

**Comment by archang** [comment]
Putting the absolute path worked - thank you for the assistance!

**Comment by gdevenyi** [comment]
@Gab-D-G we should try and figure out why preprocess with a relative path worked, but later stages didn't

Is this docker's fault? Can it reproduce with singularity?
