### ISSUE TITLE
Issue with preprocessing step

### ISSUE THREAD

**Issue by sxf-ux** [CoBrALab/RABIES#274]
Hi. Im trying to undergo the preprocessing stage. Ive downloaded the test_dataset and I have ran
 'rabies -p MultiProc preprocess input_BIDS/ preprocess_outputs/ --apply_STC --TR 1.2 --commonspace_reg masking=true,brain_extraction=false,template_registration=SyN,fast_commonspace=false'.

I get a message saying ' SOME FILES FROM THE DEFAULT TEMPLATE ARE MISSING. THEY WILL BE INSTALLED BEFORE FURTHER PROCESSING.' but I don't understand what that means. What default templates are there? I have already downloaded the templates and masks and have already exported their paths.

I am using a MacOS and I downloaded rabies using Pypi and downloaded the non-python dependencies found in dependencies.txt.

Any ideas or suggestions to help me with this would be highly appreciated since I have absolutely no idea.

**Comment by Gab-D-G** [comment]
Hi, when you execute RABIES it will look file the default template files in `~/.local/share/rabies/`. If files are missing in this folder, it will download them automatically, and then run the pipeline.
