### ISSUE TITLE
Pre-processing InhoCorrection Issue

### ISSUE THREAD

**Issue by sxf-ux** [CoBrALab/RABIES#276]
Hello.

Im doing some preprocessing right now and my workflow says that it's running Inho Correction but the job doesn't complete for some reason. I don't get an error. I've tried this using the structural anatomical images and even with the --bold_only option.

This is the command I call and it appears to finish other bold workflows such as the slice timing correction:

```
singularity run -B $DATA_DIR:/input_BIDS:ro \
-B $DATA_DIR/${sub}/$mr/preprocess_outputs:/preprocess_outputs/ \
/location/to/rabies.sif -p MultiProc preprocess /input_BIDS/ /preprocess_outputs/ --bold_only --apply_STC --TR 1.0 --commonspace_reg masking=true,brain_extraction=false,template_registration=SyN,fast_commonspace=false
```

I am assuming the above code is correct based on the scripts available on here + the documentation manual and it giving me no errors + reports appear to be giving the correct outputs with the correct inputs.

I have attached the log file when I ran it with and without bold_only. 
[rabies_preprocess.log](https://github.com/CoBrALab/RABIES/files/10849345/rabies_preprocess.log)
[rabies_preprocess_boldonly.log](https://github.com/CoBrALab/RABIES/files/10849346/rabies_preprocess_boldonly.log)

**Comment by Gab-D-G** [comment]
How long has it been running for? Depending on the resolution of your images, computational time can increase exponentially. If your anatomical resolution is low (<0.1mm isotropic), try again by downsampling the resolution with --anatomical_resampling. It can be expected that this steps runs for 1h per scan, you will want to use `-p MultiProc` for efficiency. Otherwise, if you don't think it is a computational time issue, you can try modifying the --anat_inho_cor options to troubleshoot. try `method=disable` first, that should skip inhomogeneity correction. then `method=no_reg`, which should be without registration, and so on.

**Comment by sxf-ux** [comment]
I was running it for 3 hours. I downsampled the resolution but the processing pipeline crashes with the following message:

```
nu_estimate_np_and_em: crashed while running spline_smooth (termination status=139)
nu_correct: crashed while running nu_estimate_np_and_em (termination status=65280)

```

**Comment by gdevenyi** [comment]
> I was running it for 3 hours. I downsampled the resolution but the processing pipeline crashes with the following message:
> 
> ```
> nu_estimate_np_and_em: crashed while running spline_smooth (termination status=139)
> nu_correct: crashed while running nu_estimate_np_and_em (termination status=65280)
> ```

Can you please provide the full logs to get proper context here.

**Comment by sxf-ux** [comment]
Sorry, I've attached it here! 
[rabies_preprocess_newcrash.log](https://github.com/CoBrALab/RABIES/files/10872857/rabies_preprocess_newcrash.log)

**Comment by Gab-D-G** [comment]
Hi, I now realize that the resampling if the template seem wrong. In your original log, the template gets resampled to a resolution of 2.5mmX2.5mmx2.5mm, which is not sensible for the mouse template you are using (the DSURQE). Even in your latest log, with a resolution of 0.4x0.4x0.4mm, this too low resolution, and will result in such crashes. In the original case, the template resolution was matched to your input images, so this resolution of 2.5mm should correspond to the lowest dimension of your EPI images. You should check how the voxel resolution is encoded in your niftis and make sure it is accurate.

**Comment by sxf-ux** [comment]
okay. so would the following approach makes sense then: resampling the DSURQE template (which is 0.04) to a 0.6 voxel resolution and call it out in rabies I've checked my EPI images and they're 0.6x0.6x0.6

**Comment by Gab-D-G** [comment]
this won't solve the issue, as the 0.6mm resolution is still too low for the DSURQE template and will likely crash. Are your images mouse brains? If so, I would find it very unlikely that images were acquired at a resolution of 0.6mm. The voxel resolution may have been artificially modified, as it is common to multiply by 10 voxel resolution to make mouse images compatible with human packages. Maybe this was done to your images. This is incompatible with RABIES' default template, as the anatomical dimensions of the template represent accurate anatomical dimensions (FOV width of about 2cm).

**Comment by sxf-ux** [comment]
I fixed the issue with adding my own template. However, now I get an error with my bold_gen_ref processing step.

```
singularity run -B ${atlas_folder}:/atlas -B /home1/safiyah/Downloads/sub-01/ses-1:/input_BIDS:ro \
-B /home1/safiyah/Downloads/sub-01/ses-1/preprocess_outputs:/preprocess_outputs/ \
/home1/safiyah/project/rabies.sif -p MultiProc preprocess /input_BIDS/ /preprocess_outputs/ --anat_template ${template} --brain_mask ${mask} --WM_mask ${wm} --CSF_mask ${csf} --vascular_mask ${csf} --labels ${atlas} --TR 0.005s --commonspace_resampling 0.3x0.3x0.3 --anat_autobox --commonspace_reg masking=true,brain_extraction=false,template_registration=SyN,fast_commonspace=true
```
Ive checked the TR of my fmri. I've also run this with the default 1.0 too


[rabies_preprocess.log](https://github.com/CoBrALab/RABIES/files/10921909/rabies_preprocess.log)

**Comment by Gab-D-G** [comment]
How was RABIES installed, and how was it executed (container or not)? You seem to have downloaded the software from the github repository, as you have some options that are not even part of the latest software version. It seems to be an error due to the ANTs version. Either you have found a bug with the current dev version of the software, or your version of ANTs is wrong.

**Comment by sxf-ux** [comment]
I've installed rabies using the container with the tag name being 0.4.8-dev2. -> https://hub.docker.com/r/gabdesgreg/rabies/tags . it was installed with `singularity build rabies.sif docker://gabdesgreg/rabies:tagname` but with the tag name being altered.

**Comment by Gab-D-G** [comment]
You have found a bug on the dev version. I will fix the issue for the next version, but in the meantime you could use the stable version 0.4.8, which should work fine.
