### ISSUE TITLE
Default for image_scaling = global variance

### ISSUE THREAD

**Issue by Francesca1990** [CoBrALab/RABIES#282]
Hi,

I am using RABIEs 0.4.8 - and running the confound correction step without any image_scaling selected (i.e. I did not add the 'image_scaling' function altogether), so the default should be 'None'. However, when I open my log file, it says 'image scaling = global variance' instead of none. Instead, if I add the step 'image_scaling = None', the log gets correctly updated with 'None'. Can you please clarify if this means that global_variance is applied even if I don't specify it?
Thank you!
Francesca

**Comment by Gab-D-G** [comment]
Hi Francesca, did you try printing the `rabies confound_correction --help` to see what the default is for image scaling? All the default parameters can be consulted with `--help`. It should be mentioning that the default is global variance if that was applied in your log file without you explicitly specifying it in your command.

**Comment by Francesca1990** [comment]
Hey - no I just referred to the info on the webpage where it says it's 'None', but I will check with the --help for sure, Thanks for the quick reply!
