### ISSUE TITLE
ROI_csv Analysis

### ISSUE THREAD

**Issue by sxf-ux** [CoBrALab/RABIES#284]
Hi!

Im having an issue with executing the analysis stage. So one thing I've noticed is that it it due to the `ROI_csv` command. Throughout RABIES, ive used my own template (I'm using rat data). Ive tried to input a csv and also a nifti as my ROI_csv but I don't receive any output in my `analysis_datasink `folder. if I don't put any ROI_csv parameter down in my command line, I get an output but the default csv is based on a mouse template which an issue since I don't use rat data.

my main questions are:

- is it supposed to be a labelled generic atlas? I'm using the sigma rat template

-  is it the labelled atlas that has been iterated as an output during preprocessing for each subject/session? and if so, should I call that out?

ive included a link to the csv file for the SIGMA brain atlas. I don't know if RABIES recognised its structure or if I should adjust the csv file so that it can be implemented inside RABIES.

[SIGMA_Anatomical_Brain_Atlas_ListOfStructures.csv](https://github.com/CoBrALab/RABIES/files/11204833/SIGMA_Anatomical_Brain_Atlas_ListOfStructures.csv)

[SIGMA_Anatomical_Brain_Atlas.nii.zip](https://github.com/CoBrALab/RABIES/files/11204868/SIGMA_Anatomical_Brain_Atlas.nii.zip)

thank you in advance!

**Comment by Gab-D-G** [comment]
Hi, all the ROI_csv parameter does is copying the file provided into the analysis_datasink. The main purpose of this is to make accessible the ROI names for the RABIES default. It does not actually contribute to computing the connectivity matrices, so in principle you should be able to relate your CSV file directly to the outputed matrices.
If you are not getting outputs at all in the analysis datasink there may be another errors. If this is the case provide your log file so I can take a look.

**Comment by Gab-D-G** [comment]
Hi, all the ROI_csv parameter does is copying the file provided into the analysis_datasink. The main purpose of this is to make accessible the ROI names for the RABIES default. It does not actually contribute to computing the connectivity matrices, so in principle you should be able to relate your CSV file directly to the outputed matrices.
If you are not getting outputs at all in the analysis datasink there may be another errors. If this is the case provide your log file so I can take a look.

**Comment by sxf-ux** [comment]
Hi! it works now. I have another question regarding the analysis. I want to conduct a  `--dataset_diagnosis` of my seed connectivity, and for there to be a statistical analysis, my `--scan_list` sample needs to be greater than 3. is the ` --scan_list` my bold (EPI) images or is it another scan that has been iterated as part of the rabies pipeline?

**Comment by Gab-D-G** [comment]
the `--data_diagnosis` will compute group-wise statistics, like correlations and standard deviation, which don't work with less than 3 samples. If there wasn't at least 3 scans that you provided to begin with, those extra steps won't be computed. With the `--scan_list` option you can specify if you want to conduct analysis on a subset of your scans provided during preprocessing, but by defaults all the scans are used, so unless you were using `--scan_list`, this means you had less than 3 scans during preprocessing.
