### ISSUE TITLE
RABIES fails on test data 

### ISSUE THREAD

**Issue by benhibou** [CoBrALab/RABIES#294]
RABIES fails on test data as nii2mnc cannot read some temporary file:

+ ThresholdImage 3 /tmp/tmp.CtNKikjjut/modelfile.mnc /tmp/tmp.CtNKikjjut/bgmask.h5 1e-12 Inf 1 0
/raid1/bboulat/antsbin/ITKv5/Modules/ThirdParty/MINC/src/libminc/libsrc2/volume.c:1403 (from MINC): Unable to open file '/tmp/tmp.CtNKikjjut/modelfile.mnc'
Exception caught during reference file reading

itk::ExceptionObject (0x55592345efe0)
Location: "unknown"
File: /raid1/bboulat/antsbin/ITKv5/Modules/IO/MINC/src/itkMINCImageIO.cxx
Line: 312
Description: ITK ERROR: MINCImageIO(0x55592345c460): Could not open file "/tmp/tmp.CtNKikjjut/modelfile.mnc".
THIS LAST LINE IS LINE 365 IN THE LOG FILE
LAST INSTANCE OF "modelfile.mnc" BEING WRITTEN IS AT LINE 

Checking the file "/tmp/tmp.CtNKikjjut/modelfile.mnc" does exist:

ls -l /tmp/tmp.CtNKikjjut/modelfile.mnc
-rw-rw-r-- 1 spectro spectro 9171316 Jun 28 14:57 /tmp/tmp.CtNKikjjut/modelfile.mnc

Running as "sudo" does not change the issue.

**Describe RABIES call**
~/.local/bin/rabies -p MultiProc preprocess ../../../RABIES/test_dataset preprocess_outputs/  --TR 1.5 --commonspace_reg masking=true,brain_extraction=false,template_registration=SyN,fast_commonspace=false >mon_run2

**Attach log file**
[monrun2.txt](https://github.com/CoBrALab/RABIES/files/11894814/monrun2.txt)
[rabies_preprocess.log](https://github.com/CoBrALab/RABIES/files/11894866/rabies_preprocess.log)

Attach to your issue the .log files present in the output folder. (e.g. rabies_out/rabies_preprocess.log)

**Additional context**
minc version 1.9.18
ANTs Version: 2.4.4.post19-ge61fa52
Ubuntu 16.04 LTS

Thanks for helping,

Ben

**Comment by Gab-D-G** [comment]
Hi Ben,

I see that you are using a local implementation of RABIES (~/.local/bin/rabies), and it seems that an error is arising somewhere from MINC or ANTs. I can't tell from here what's happening. why not use a Docker/Singularity installation? Otherwise you will have to debug:
```ThresholdImage 3 /tmp/tmp.CtNKikjjut/modelfile.mnc /tmp/tmp.CtNKikjjut/bgmask.h5 1e-12 Inf 1 0
/raid1/bboulat/antsbin/ITKv5/Modules/ThirdParty/MINC/src/libminc/libsrc2/volume.c:1403 (from MINC): Unable to open file '/tmp/tmp.CtNKikjjut/modelfile.mnc```

**Comment by gdevenyi** [comment]
Closing as stale. Supported run versions are docker and singularity/apptainer.
