### ISSUE TITLE
testing data with Rabies 

### ISSUE THREAD

**Issue by nmskhan** [CoBrALab/RABIES#296]
Hi All
Thank you for sharing your software, I successfully installed rabies in my iMac system (using pip install) and I was trying to test your sample data and I ended up with an error in running preprocessing. No errors during the installation- See below.

(base) kh@PSC-787-Nk rabies_test_dataset % rabies -p Linear preprocess Users/kh/Documents/rabies_test_dataset Users/kh/Documents/rabies_test_dataset/preprocess_outputs --apply_STC --TR 1.2 --commonspace_reg masking=true,brain_extraction=false,template_registration=SyN,fast_commonspace=false

230719-11:21:48,456 nipype.workflow INFO:
	 SOME FILES FROM THE DEFAULT TEMPLATE ARE MISSING. THEY WILL BE INSTALLED BEFORE FURTHER PROCESSING.
230719-11:22:50,270 nipype.workflow WARNING:
	   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 65.2M  100 65.2M    0     0  1975k      0  0:00:33  0:00:33 --:--:-- 2253k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 69.2M  100 69.2M    0     0  2568k      0  0:00:27  0:00:27 --:--:-- 2747k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  431k  100  431k    0     0  1551k      0 --:--:-- --:--:-- --:--:-- 1586k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 13600  100 13600    0     0   191k      0 --:--:-- --:--:-- --:--:--  210k
/Users/kh/miniconda3/bin/install_DSURQE.sh: line 15: mnc2nii: command not found

Traceback (most recent call last):
  File "/Users/kh/miniconda3/bin/rabies", line 3, in <module>
    execute_workflow()
  File "/Users/kh/miniconda3/lib/python3.9/site-packages/rabies/run_main.py", line 31, in execute_workflow
    install_DSURQE(log)
  File "/Users/kh/miniconda3/lib/python3.9/site-packages/rabies/run_main.py", line 320, in install_DSURQE
    rc = run_command(f'install_DSURQE.sh {rabies_path}', verbose=True)
  File "/Users/kh/miniconda3/lib/python3.9/site-packages/rabies/utils.py", line 312, in run_command
    process = subprocess.run(
  File "/Users/kh/miniconda3/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args, 
subprocess.CalledProcessError: Command 'install_DSURQE.sh /Users/kh/.local/share/rabies' returned non-zero exit status 127.

I do not see any files in cd ~/.local/share/rabies/ except this file (DSURQE_40micron_R_mapping.csv).
Is there anything wrong with this command or files are missing? Please let me know 

Ned

**Comment by Gab-D-G** [comment]
Hi Ned,

You do not seem to have minc-toolkit installed (mnc2nii: command not found), which is part of the dependencies for RABIES (in https://github.com/CoBrALab/RABIES/blob/master/dependencies.txt). I strongly recommend trying the software through Singularity (or Docker), where you only need to download an image from docker hub that already has all dependencies. See instructions on the online documentation on how to carry out this installation. This would greatly simplify troubleshooting for you, otherwise you will need to handle proper installation of all dependencies listed.

Best,
Gabe DG

**Comment by nmskhan** [comment]
Thanks Gabe for your input. 
I tried to install this via docker, but I do have an error in pulling the rabies via docker. The following is the error.

ned%docker pull  gabdesgreg/rabies:latest
Error response from daemon: manifest for gabdesgreg/rabies:latest not found: manifest unknown: manifest unknown
ned% docker pull gabdesgreg/rabies:tagname
Error response from daemon: manifest for gabdesgreg/rabies:tagname not found: manifest unknown: manifest unknown

Any idea? Thanks
ned

**Comment by nmskhan** [comment]
Thanks, I was able to run it with the file downloaded from that interface.

**Comment by Gab-D-G** [comment]
Amazing!
