### ISSUE TITLE
The spatial smoothing step creates data point outside the brain mask

### ISSUE THREAD

**Issue by Gab-D-G** [CoBrALab/RABIES#320]
The current implementation of spatial smoothing takes a full 4D image and smooth everything, which creates data outside the brain mask https://github.com/CoBrALab/RABIES/blob/2bd3803e1941ca9b0f3b6f828c5d4be537c82989/rabies/confound_correction_pkg/confound_correction.py#L493. Ideally, the smoothing filter should only consider voxels within the brain.

**Comment by gdevenyi** [comment]
well, masking should probably happen after smoothing.

But to a first approximation as well:
`s(X with mask) = s(Mask*X)/s(Mask)`

**Comment by Gab-D-G** [comment]
we will apply a division by the smoothed mask like FSL https://johnmuschelli.com/fslr/reference/fslsmooth.html to correct for the edge effect
