### ISSUE TITLE
the brain mask is smaller than the template

### ISSUE THREAD

**Issue by lvqianmri** [CoBrALab/RABIES#359]
**Describe the bug**
Hi. 
 I can finish the pipeline successfully, but I found that the brain mask in the commonspace_mask file is smaller than the template. Please see attached image.
**Describe RABIES call**
Include a copy of the command call you executed from the terminal, and any additional information that could be relevant to your execution.

**Attach log file**
Attach to your issue the .log files present in the output folder. (e.g. rabies_out/rabies_preprocess.log)
![brainmask_smaller](https://github.com/CoBrALab/RABIES/assets/162289453/02607d44-2421-440b-aad9-8373a1ab418f)
![brainmask_smaller](https://github.com/CoBrALab/RABIES/assets/162289453/79ea9461-7d8c-4dd4-a3fd-7eab8ba48c05)

**Attach QC_report**
Attach to your issue the QC_report folder present in the output folder. If QC_report is too large, mention that it couldn't be shared, and if possible, provide an alternative access to the files.

**Additional context**

**Comment by gdevenyi** [comment]
Please provide information requested in the template.

**Comment by Gab-D-G** [comment]
Can you compare to the resampled template outputted by RABIES https://rabies.readthedocs.io/en/latest/outputs.html#preprocessing-outputs:~:text=commonspace_resampled_template? This one should match the mask. Your original template file is higher resolution than your EPI seemingly, so the resampling may have to approximate the boundaries and cut out some information to match the lower resolution of your EPI.
