### ISSUE TITLE
No output in /analysis_datasink if --data_diagnosis tag is excluded

### ISSUE THREAD

**Issue by david-roper** [CoBrALab/RABIES#378]
**Describe the bug**
I have test running the RABIES analysis stage on the zenodo test_dataset and noticed that if the --data-diagnosis tag is not included within the analysis run there is no output in /analysis_datasink.  Is this behavior intended? 

**Describe RABIES call**
Include a copy of the command call you executed from the terminal, and any additional information that could be relevant to your execution.

The /test_dataset_outputs directory initially contains the outputs of the confound_correction stage.

```singularity run -B $PWD/test_dataset:/test_dataset:ro -B $PWD/test_dataset_outputs:/test_dataset_outputs/ rabies_0.4.8.sif -p MultiProc --local_threads 4 analysis /test_dataset_outputs/ /test_dataset_outputs ```

**Attach log file**
Attach to your issue the .log files present in the output folder. (e.g. rabies_out/rabies_preprocess.log)

[rabies_analysis.log](https://github.com/user-attachments/files/16113464/rabies_analysis.log)

**Attach QC_report**
Attach to your issue the QC_report folder present in the output folder. If QC_report is too large, mention that it couldn't be shared, and if possible, provide an alternative access to the files.

[preprocess_QC_report.zip](https://github.com/user-attachments/files/16113492/preprocess_QC_report.zip)

**Additional context**

RABIES version : 0.4.8
Apptainer version: 1.2.5

**Comment by Gab-D-G** [comment]
This is normal, since at least one analysis option should be selected to generate any output (dual regression, seed connectivity ...). Data diagnosis automatically runs dual regression.

**Comment by david-roper** [comment]
That makes sense, thank you for the clarification.
