### ISSUE TITLE
remove --bids_input mention in readme.md

### ISSUE THREAD

**Issue by grandjeanlab** [CoBrALab/RABIES#65]
The option is no longer apparent in the rabies code. 
does that mean old pseudo-bids is no longer supported?

**Comment by Gab-D-G** [comment]
Indeed the old input folder structure was removed and now only the BIDS format is accepted. It was changed in the last commits. The README will be updated before the next official version.

**Comment by grandjeanlab** [comment]
Do you think it is possible to implement a more liberal bids format? At the moment, it seems to require: 'sub', 'ses', and 'run' tags in the file names, but 'ses' and 'run' are optional in the BIDS format.

**Comment by gdevenyi** [comment]
It looks like while we're depending on pybids, we have a hand-rolled bids interface at:
https://github.com/CoBrALab/RABIES/blob/master/rabies/preprocess_bold_pkg/interfaces/bids.py

If we stick with pybids interfaces, we should be following the standard very closely, since its from the folks who wrote the standards.

**Comment by Gab-D-G** [comment]
The BIDS interface that's actually used is found in https://github.com/CoBrALab/RABIES/blob/master/rabies/preprocess_bold_pkg/utils.py. The https://github.com/CoBrALab/RABIES/tree/master/rabies/preprocess_bold_pkg/interfaces folder is from fmriprep, and only a few functions from there are used. It is probably possible to develop a more flexible BIDS reader, but it might require a major software update. I'll look into it. Maybe relying on https://github.com/CoBrALab/RABIES/blob/master/rabies/preprocess_bold_pkg/interfaces/bids.py could be a way to go.

**Comment by grandjeanlab** [comment]
I can work with the parser as is. As long as it is clear the 'ses' and 'run' tags are necessary in the final readme file.
