### ISSUE TITLE
translation parameters are ploted as rotation, and rotation as translations. 

### ISSUE THREAD

**Issue by grandjeanlab** [CoBrALab/RABIES#66]
https://github.com/CoBrALab/RABIES/blob/3a3db2222aaf7a0d306faf621453e6a4a0e00d4b/rabies/shell_scripts/plot_motion_traces.sh#L6

correct code should read: 
fsl_tsplot -i $mc_par -t 'antsMotionCorr estimated rotations (radians)' -u 1 --start=1 --finish=3 -a roll,pitch,yaw -w 640 -h 144 -o rot.png
fsl_tsplot -i $mc_par -t 'antsMotionCorr estimated translations (mm)' -u 1 --start=4 --finish=6 -a dS,dL,dP -w 640 -h 144 -o trans.png

**Comment by Gab-D-G** [comment]
This issue is actually quite confusing. I am using antsMotionCorr for motion realignment, and they don't specify which parameter correspond to translations or rotations. I have tried comparing results from antsMotionCorr and your script using 3dvolreg, but they don't even provide similar motion traces. I will have to investigate this further and try testing whether 3dvolreg or antsMotionCorr does a better job at motion realignment. I'm definitely open to suggestions regarding!

**Comment by gdevenyi** [comment]
It is the raw affine matrix:
https://sourceforge.net/p/advants/discussion/840260/thread/c69ac60d47/

**Comment by gdevenyi** [comment]
This is why you're supposed to be using antsMotionCorrStats to post-process the results:
```
COMMAND: 
     antsMotionCorrStats
          antsMotionCorrStats - create summary measures of the parameters that are output 
          by antsMotionCorr. Currently only works for linear transforms. Outputs the mean 
          and max displacements for the voxels within a provided mask, at each time point. 
          By default the displacements are relative to the reference space, but the 
          framewise option may be used to provide displacements between consecutive time 
          points 

OPTIONS: 
     -x, --mask mask.nii.gz
          Mask image - compute displacements within mask. 

     -m, --moco MOCOparams.csv
          motion correction parameters from antsMotionCorr. 

     -o, --output corrected.csv
          Specify the output file 

     -t, --transform 
          Specify the index for a 3D transform to output 

     -f, --framewise 
          do framewise summarywise stats 
          <VALUES>: 0

     -s, --spatial-map 
          output image of displacement magnitude 

     -d, --timeseries-displacement 
          output 4d time-series image of displacement magnitude 

     -h 
          Print the help menu (short version). 
          <VALUES>: 0

     --help 
          Print the help menu. 
          <VALUES>: 0
```

We talked about the timeseries-displacement as a voxel-wise motion covariate map previously.

**Comment by Gab-D-G** [comment]
I don't think this can output the 3 translation and 3 rotation parameters unfortunately. It can output absolute and framewise displacement magnitude within a mask, or create voxelwise spatial map of these displacements. I was quite sure the 6 rigid body parameters were in the MOCOparams.csv .

**Comment by gdevenyi** [comment]
The parameters should be serialized accoring to this for Affine:
> To support the registration framework, the transform parameters can also be set as an Array<double> of size (NDimension + 1) * NDimension using method SetParameters(). The first (NDimension x NDimension) parameters defines the matrix in row-major order (where the column index varies the fastest). The last NDimension parameters defines the translation in each dimensions.

https://itk.org/Doxygen/html/classitk_1_1AffineTransform.html

And this for Rigid3D
> The serialization of the optimizable parameters is an array of 12 elements. The first 9 parameters represents the rotation matrix in row-major order (where the column index varies the fastest). The last 3 parameters defines the translation in each dimension.

https://itk.org/Doxygen/html/classitk_1_1Rigid3DTransform.html

**Comment by grandjeanlab** [comment]
> comparing

I noticed that in most mouse fMRI there is a drift along the SI axis, and observed it was in the rotation plot rather than the translation plot. 
that's what put me on track for this bug
