### ISSUE TITLE
PBS issue. 

### ISSUE THREAD

**Issue by grandjeanlab** [CoBrALab/RABIES#82]
I'm having two issues running RABIES on my HPC with PBS: 
1) In `twolevel_dbm.py `, when `antsMultivariateTemplateConstruction2.sh` is called, could the `-o` output option be given with the full path rather than relative path? My PBS system (and I assume others) by default runs scripts relative to $HOME, rather than in the folder where `qsub` was initiated.  

2) In `antsMultivariateTemplateConstruction2.sh`, in the shell script, command ` -q nopreempt` on line 1064 prevents PBS to run under some conditions, including mine, also reported here (https://sourceforge.net/p/advants/discussion/840261/thread/3bccddeb/) 

Could it be removed?

**Comment by gdevenyi** [comment]
1. This sounds like an issue with the ants script rather than rabies/twolevel
2. Same with ants here.

My qbatch version probably avoids both these issues I suspect, we can test.

**Comment by Gab-D-G** [comment]
I believe this is now solved. Feel free to re-open the issue if necessary.
