### ISSUE TITLE
anat_preproc.sh template_mask

### ISSUE THREAD

**Issue by grandjeanlab** [CoBrALab/RABIES#83]
I get a lot of Anat_Preproc error in versin 0.1.3
from `shell_scripts/anat_preproc.sh: line 14: template_mask: unbound variable` error message, it seems that REGMASK is defined with $template_mask, however this argument is not provided from an argument when  anat_preproc.sh gets called.

**Comment by grandjeanlab** [comment]
the current version (on github) of sheel_scripts/anat_preproc.sh still has the buggy line on 14. `REGMASK=$template_mask`

**Comment by gdevenyi** [comment]
It doesn't seem to be an argument but rather an environment variable being set??? This is a weird choice..
https://github.com/CoBrALab/RABIES/blob/477c650bba31ca75335a58898b58fabff128ecaa/rabies/run_main.py#L237

I don't think this is how this should be handled.

**Comment by Gab-D-G** [comment]
I will change this so that all variables are in python.
