### ISSUE TITLE
add niflow-nipype1-workflows as a dependency

### ISSUE THREAD

**Issue by grandjeanlab** [CoBrALab/RABIES#85]
https://github.com/CoBrALab/RABIES/blob/995689c793c49af54f993fd9dfc45748de0c9eec/dependencies.txt#L25

While running latest with nipype==1.5.0 I had the following issue. 
No module named 'nipype.workflows.smri'

I had to pip install niflow-nipype1-workflows to continue.

**Comment by Gab-D-G** [comment]
Thanks for the notice, this will be corrected in the next release!
