### ISSUE TITLE
optimize RABIES

### ISSUE THREAD

**Issue by grandjeanlab** [CoBrALab/RABIES#86]
it takes >12h on my HPC to run a 3 anat + 3 func test dataset in serial mode. 

every step should be optimized. e.g. currently ants_MC takes 30min for a 300 volume scan. 

Other toolboxes with default parameters would run it <3min (e.g. 3dvolreg in AFNI).

**Comment by grandjeanlab** [comment]
AFNI's 3dvolreg took 25 seconds for the same func scan that was timed to take 30 min with ants_MC using RABIES (estimated using nipype time-stamps). I find the output sufficient but didn't compare numerically the output vs ANTs. 

IMO the issue applies to every step of RABIES, not just ants_MC.  

I don't think it is a matter of changing to another function, as much as optimizing ANTs' functions (number of iterations both at the interpolation level and within the interpolation levels.).  Or at least have a  '-fast' option with more lenient parameters.

**Comment by gdevenyi** [comment]
FYI, this long processing time per subject is currently in line with how long "good" human processing takes (fMRIprep), so we shouldn't necessarily be pushing for maximum speed at the cost of poor processing.

**Comment by gdevenyi** [comment]
Providing an annotated log for timings might be helpful here so we have a sense of current runtimes.

**Comment by grandjeanlab** [comment]
a three anat/func serial preprocessing exceeded my HPC max walltime of 72h, so I cannot give an exact runtime :-) 

in comparison, I ran a comparable three anat/func serial preprocessing of human data with fMRIprep 20.0.6 in ~30h.
