### ISSUE TITLE
run_main.py allows arbitrary nipype runtime plugins resulting in crash

### ISSUE THREAD

**Issue by ChristianNSchmitz** [CoBrALab/RABIES#88]
Dear Rabies-Team,
thanks a lot for this great toolbox!
I was trying to set up the docker execution of rabies, however I stumbled over following error and would like to ask you for your help:

```

root@CUJHQY1:/mnt/d/LinuxSubsystem/RABIES-master# docker run -it --rm -v /mnt/d/PsiAlc/Test:/niiinputs:ro -v /mnt/d/PsiAlc/Test:/outputs gabdesgreg/rabies:latest -preprocess /niiinputs /outputs

pixdim[0] (qfac) should be 1 (default) or -1; setting qfac to 1
pixdim[0] (qfac) should be 1 (default) or -1; setting qfac to 1
pixdim[0] (qfac) should be 1 (default) or -1; setting qfac to 1
Running main workflow with reprocess plugin.
Traceback (most recent call last):
  File "/home/rabies/RABIES-0.1.3/exec.py", line 13, in <module>
    execute_workflow()
  File "/home/rabies/RABIES-0.1.3/rabies/run_main.py", line 291, in execute_workflow
    workflow.run(plugin=plugin, plugin_args = {'max_jobs':50,'dont_resubmit_completed_jobs': True, 'n_procs' : int(os.environ["local_threads"]), 'qsub_args': '-pe smp %s' % (os.environ["min_proc"])})
  File "/home/rabies/miniconda-latest/envs/rabies/lib/python3.6/site-packages/nipype/pipeline/engine/workflows.py", line 578, in run
    plugin_mod = getattr(sys.modules[name], '%sPlugin' % plugin)
AttributeError: module 'nipype.pipeline.plugins' has no attribute 'reprocessPlugin'
```

Thank you very much for your support!
Best,
Christian

**Comment by gdevenyi** [comment]
You have a typo on your command line: ``-preprocess`` which argparse is interpreting as ``-p reprocess`` which is being passed as an execution plugin for nipype workflows which does not exist.

@Gab-D-G The ``-p`` option should limit the possible options it takes in, see https://github.com/CoBrALab/twolevel_ants_dbm/blob/master/twolevel_dbm.py#L815-L826 for an example.

**Comment by Gab-D-G** [comment]
Hi Christian, Thanks a lot for giving it a try and for your input! The error will be corrected in the next release. Don't hesitate if you run into further issues!
