### ISSUE TITLE
Docker Error: unable to fund image 'rabies:latest' locally

### ISSUE THREAD

**Issue by cowry09** [CoBrALab/RABIES#96]
Did anyone else get this error?

After pulling the latest image from the docker hub, I was able to run "docker run gabdesgreg/rabies:latest -h" to get the help information, but when I tested it using the provided example data. It gave me this error:
![image](https://user-images.githubusercontent.com/50677308/100523580-8fe9bd80-317f-11eb-9109-75eb84457729.png)

The command line was like this: 
docker run -it --rm 
-v C:/Projects/Penn/RABIES_Test/test_dataset/test_dataset:/test_dataset:to 
-v C:/Projects/Penn/RABIES_Test/test_dataset/test_output:/output_folder 
rabies test_dataset/ output_folder/ --anatomical_resampling 0.4x0.4x0.4

Thanks so much
Taotao

**Comment by gdevenyi** [comment]
`docker pull  gabdesgreg/rabies:latest` works for me. Perhaps you're having issues with either your networking, your docker installation, or you have modified your docker registry config to use an alternative than the dockerhub default?

**Comment by Gab-D-G** [comment]
Hi, I believe your error arises because you must specify 'gabdesgreg/rabies' when calling the container, and not only 'rabies'. Hope this helps!
