### ISSUE TITLE
fast_commonspace misregistration

### ISSUE THREAD

**Issue by grandjeanlab** [CoBrALab/RABIES#97]
when I use fast_commonspace=TRUE, the content of the commonspace_datasink looks like the example below. It seems the content of 'warped_template' undergoes two registrations. *_RAS_preproc_output_warped_image.nii.gz and *_RAS_preproc_output_warped_image_output_warped_image.nii.gz are slightly out of registrations with one another. 

commonspace_datasink/
├── ants_dbm_template
│   ├── _scan_info_subject_id338246.session1_split_name_sub-338246_ses-1_acq_RARE_T2w
│   │   └── sub-338246_ses-1_acq_RARE_T2w_RAS_preproc_output_warped_image.nii.gz
│   └── _scan_info_subject_id388247.session1_split_name_sub-388247_ses-1_acq_RARE_T2w
│       └── sub-388247_ses-1_acq_RARE_T2w_RAS_preproc_output_warped_image.nii.gz
└── warped_template
    ├── _scan_info_subject_id338246.session1_split_name_sub-338246_ses-1_acq_RARE_T2w
    │   └── sub-338246_ses-1_acq_RARE_T2w_RAS_preproc_output_warped_image_output_warped_image.nii.gz
    └── _scan_info_subject_id388247.session1_split_name_sub-388247_ses-1_acq_RARE_T2w
        └── sub-388247_ses-1_acq_RARE_T2w_RAS_preproc_output_warped_image_output_warped_image.nii.gz

This also shows in  Template2Commonspace.png QA output which seems to use the *_RAS_preproc_output_warped_image_output_warped_image.nii.gz image, leading to slight misregistration on the SI axis, rather than the correctly registered *_RAS_preproc_output_warped_image.nii.gz

![Template2Commonspace](https://user-images.githubusercontent.com/22633767/103626678-d7145c80-4f3c-11eb-8977-0f279ca3bd9f.png)

**Comment by grandjeanlab** [comment]
seems like the issue is in: 
rabies/shell_scripts/null_nonlin.sh

Possibly due to 
line 21 :   --initial-moving-transform [$fixed,$moving,1] \

This performs a centre of mass initial registration based on image intensities. 

Replacing to 
line 21 :   --initial-moving-transform [$fixed,$moving,2] \

seems to correct this. @Gab-D-G , could you please test, correct, and push new version?

**Comment by gdevenyi** [comment]
`line 21 : --initial-moving-transform [$fixed,$moving,2] \`

Hi @grandjeanlab, the kind of change you propose here would change the initialization from a center-of-mass, to "origin" which would match the originating corner of the volumes. The problem is such an approach is that it highly dependent on the field-of-view of the images, if they are largely mismatched then you will not have sufficient overlap to bootstrap the rest of the registration.

Did you try mode "0" which initializes using the geometric center of the volumes (this also has FOV issues, though less so than using a corner)

**Comment by gdevenyi** [comment]
@Gab-D-G this script does not appear to use my optimized https://github.com/CoBrALab/minc-toolkit-extras/blob/master/ants_generate_iterations.py script for the affine.

As for the "null" nonlin:
https://github.com/CoBrALab/RABIES/blob/master/rabies/shell_scripts/null_nonlin.sh#L24

You could instead just do
```
  --transform SyN[0.2,2,0] --metric CC[$fixed,$moving,1,4] --convergence [0,1e-6,10] \
    --shrink-factors 1 \
    --smoothing-sigmas 0 \
```

I presume you want to create an empty nonlinear file so the rest of the pipeline doesn't have to be modified here.

**Comment by Gab-D-G** [comment]
The proposed PR by @grandjeanlab included ```  --initial-moving-transform [$fixed,$moving,2] \ ``` in the 'null' script. @gdevenyi Should this be changed to ```  --initial-moving-transform [$fixed,$moving,0] \ ``` to mitigate initialization errors?
I will also update to https://github.com/CoBrALab/minc-toolkit-extras/blob/master/ants_generate_iterations.py.

**Comment by grandjeanlab** [comment]
technically, because both the moving image and fixed image entering the 'null' script should be in the same space, we could remove the `--initial-moving-transform` altogether without any detrimental effect. Only the `--initial-moving-transform [$fixed,$moving,1]` option causes an errur because it applies 'center-of-mass'  which can induce unwanted translation between $fixed and #mvoing.

**Comment by gdevenyi** [comment]
If that's the intent of null script, then yes, you should remove the `--initial-moving-transform` altogether.

**Comment by gdevenyi** [comment]
Would appreciate a comment block at the top of the script describing what the purpose of it is.

**Comment by Gab-D-G** [comment]
Great, thanks both of you for the feedback! The line will be removed, and I added further description on top of the script.
